name: 'code checks'
on:
  [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '12.x'

    - name: 'install'
      run: npm run init

    - name: 'test'
      run: npm run test

  build_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '12.x'

    - name: 'install'
      run: npm run init

    - name: 'build'
      run: npm run build
