name: 'code checks'
on:
  [pull_request]

jobs:
  # джоба для запуска тестов
  test_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '16.x'

    - name: 'install'
      run: npm i

    - name: 'test'
      run: npm run test

  # джоба для запуска линтера
  eslint_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '16.x'

    - name: 'install'
      run: npm i

    - name: 'eslint'
      run: npm run eslint

  # джоба для проверки компизации ts
  tsc_job:
    needs: [eslint_job]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '16.x'

    - name: 'install'
      run: npm i

    - name: 'compile ts'
      run: npm run compile

  # джоба для проверки билда
  build_job:
    needs: [tsc_job]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '16.x'

    - name: 'install'
      run: npm i

    - name: 'build'
      run: npm run build
